# Generated by Django 3.2.10 on 2022-02-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_device', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('subarea', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Iot_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('variable', models.CharField(max_length=250)),
                ('measure', models.CharField(default='None', max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_api.inventory')),
            ],
        ),
    ]
