# Generated by Django 3.2.10 on 2021-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device',
            name='measure',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
