# Generated by Django 3.2.10 on 2021-12-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_api', '0002_alter_iot_device_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iot_dots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_date', models.DateField(auto_now_add=True)),
                ('measure', models.CharField(default='None', max_length=250)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_api.iot_device')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_api.inventory')),
            ],
        ),
    ]
