# Generated by Django 3.2.10 on 2022-02-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_api', '0002_iot_dots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iot_dots_ampers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_date', models.DateTimeField(auto_now_add=True)),
                ('value_amper', models.FloatField(default='None')),
                ('value_volt', models.FloatField(default='None')),
                ('measure_amper', models.CharField(default='None', max_length=250)),
                ('measure_volt', models.CharField(default='None', max_length=250)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_api.iot_device')),
            ],
        ),
        migrations.DeleteModel(
            name='Iot_dots',
        ),
    ]
