# Generated by Django 3.2.10 on 2021-12-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_api', '0003_iot_dots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_dots',
            name='measure_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
