# Generated by Django 3.2.10 on 2022-03-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_api', '0003_auto_20220208_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iot_tag_dot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_date', models.DateTimeField(auto_now_add=True)),
                ('tag_number', models.IntegerField()),
            ],
        ),
    ]
