# Generated by Django 3.2.10 on 2021-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_api', '0004_alter_iot_dots_measure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_dots',
            name='value',
            field=models.FloatField(),
        ),
    ]
