# Generated by Django 3.2.10 on 2022-03-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_api', '0004_iot_tag_dot'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_tag_dot',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_api.iot_device'),
        ),
    ]
